{"name": "test_contacts_content[PHONE]", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.TimeoutException: Message: \nStacktrace:\n#0 0x6542c1d22c7a <unknown>\n#1 0x6542c1a05e2c <unknown>\n#2 0x6542c1a52661 <unknown>\n#3 0x6542c1a52751 <unknown>\n#4 0x6542c1a96f64 <unknown>\n#5 0x6542c1a755ed <unknown>\n#6 0x6542c1a94303 <unknown>\n#7 0x6542c1a75363 <unknown>\n#8 0x6542c1a45247 <unknown>\n#9 0x6542c1a45b9e <unknown>\n#10 0x6542c1ce924b <unknown>\n#11 0x6542c1ced2f1 <unknown>\n#12 0x6542c1cd4afe <unknown>\n#13 0x6542c1cede52 <unknown>\n#14 0x6542c1cb979f <unknown>\n#15 0x6542c1d12638 <unknown>\n#16 0x6542c1d12810 <unknown>\n#17 0x6542c1d21dac <unknown>\n#18 0x748175894ac3 <unknown>", "trace": "self = <UkrNet.tests.test_login_page.TestLoginPage object at 0x762927f7d8a0>\nopen_login_page = <UkrNet.page_objects.login_page.LoginPage object at 0x762927f41ea0>\ncontact = 'PHONE'\n\n    @allure.suite('Footer')\n    @allure.testcase('https://app.qase.io/case/PF-31', 'Contacts content')\n    @allure.severity('normal')\n    @pytest.mark.parametrize('contact', ER.get_all_support_contacts())\n    def test_contacts_content(self, open_login_page, contact):\n        login_page = open_login_page\n        with allure.step(f'Check content of {contact} contact'):\n            expected_content = ER.get_support_content()[contact]\n>           actual_content = login_page.get_support_content(contact)\n\ntest_login_page.py:330: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n../page_objects/login_page.py:276: in get_support_content\n    return self.__get_support_phone_content()\n../page_objects/login_page.py:124: in __get_support_phone_content\n    return self._get_text(self.__support_phone_content)\n../utilities/web_ui/base_page.py:134: in _get_text\n    return self.__wait_until_element_visible(locator).text\n../utilities/web_ui/base_page.py:34: in __wait_until_element_visible\n    return self.__wait.until(EC.visibility_of_element_located(locator))\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <selenium.webdriver.support.wait.WebDriverWait (session=\"0028cd6744547fe41cd3fec79f2a5335\")>\nmethod = <function visibility_of_element_located.<locals>._predicate at 0x762927ec7880>\nmessage = ''\n\n    def until(self, method: Callable[[D], Union[Literal[False], T]], message: str = \"\") -> T:\n        \"\"\"Calls the method provided with the driver as an argument until the \\\n        return value does not evaluate to ``False``.\n    \n        :param method: callable(WebDriver)\n        :param message: optional message for :exc:`TimeoutException`\n        :returns: the result of the last call to `method`\n        :raises: :exc:`selenium.common.exceptions.TimeoutException` if timeout occurs\n        \"\"\"\n        screen = None\n        stacktrace = None\n    \n        end_time = time.monotonic() + self._timeout\n        while True:\n            try:\n                value = method(self._driver)\n                if value:\n                    return value\n            except self._ignored_exceptions as exc:\n                screen = getattr(exc, \"screen\", None)\n                stacktrace = getattr(exc, \"stacktrace\", None)\n            time.sleep(self._poll)\n            if time.monotonic() > end_time:\n                break\n>       raise TimeoutException(message, screen, stacktrace)\nE       selenium.common.exceptions.TimeoutException: Message: \nE       Stacktrace:\nE       #0 0x6542c1d22c7a <unknown>\nE       #1 0x6542c1a05e2c <unknown>\nE       #2 0x6542c1a52661 <unknown>\nE       #3 0x6542c1a52751 <unknown>\nE       #4 0x6542c1a96f64 <unknown>\nE       #5 0x6542c1a755ed <unknown>\nE       #6 0x6542c1a94303 <unknown>\nE       #7 0x6542c1a75363 <unknown>\nE       #8 0x6542c1a45247 <unknown>\nE       #9 0x6542c1a45b9e <unknown>\nE       #10 0x6542c1ce924b <unknown>\nE       #11 0x6542c1ced2f1 <unknown>\nE       #12 0x6542c1cd4afe <unknown>\nE       #13 0x6542c1cede52 <unknown>\nE       #14 0x6542c1cb979f <unknown>\nE       #15 0x6542c1d12638 <unknown>\nE       #16 0x6542c1d12810 <unknown>\nE       #17 0x6542c1d21dac <unknown>\nE       #18 0x748175894ac3 <unknown>\n\n../../.venv/lib/python3.10/site-packages/selenium/webdriver/support/wait.py:105: TimeoutException"}, "steps": [{"name": "Check content of PHONE contact", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.TimeoutException: Message: \nStacktrace:\n#0 0x6542c1d22c7a <unknown>\n#1 0x6542c1a05e2c <unknown>\n#2 0x6542c1a52661 <unknown>\n#3 0x6542c1a52751 <unknown>\n#4 0x6542c1a96f64 <unknown>\n#5 0x6542c1a755ed <unknown>\n#6 0x6542c1a94303 <unknown>\n#7 0x6542c1a75363 <unknown>\n#8 0x6542c1a45247 <unknown>\n#9 0x6542c1a45b9e <unknown>\n#10 0x6542c1ce924b <unknown>\n#11 0x6542c1ced2f1 <unknown>\n#12 0x6542c1cd4afe <unknown>\n#13 0x6542c1cede52 <unknown>\n#14 0x6542c1cb979f <unknown>\n#15 0x6542c1d12638 <unknown>\n#16 0x6542c1d12810 <unknown>\n#17 0x6542c1d21dac <unknown>\n#18 0x748175894ac3 <unknown>\n\n", "trace": "  File \"/home/ubuntu/PycharmProjects/UkrNet_portfolio/UkrNet/tests/test_login_page.py\", line 330, in test_contacts_content\n    actual_content = login_page.get_support_content(contact)\n  File \"/home/ubuntu/PycharmProjects/UkrNet_portfolio/UkrNet/page_objects/login_page.py\", line 276, in get_support_content\n    return self.__get_support_phone_content()\n  File \"/home/ubuntu/PycharmProjects/UkrNet_portfolio/UkrNet/page_objects/login_page.py\", line 124, in __get_support_phone_content\n    return self._get_text(self.__support_phone_content)\n  File \"/home/ubuntu/PycharmProjects/UkrNet_portfolio/UkrNet/utilities/web_ui/base_page.py\", line 134, in _get_text\n    return self.__wait_until_element_visible(locator).text\n  File \"/home/ubuntu/PycharmProjects/UkrNet_portfolio/UkrNet/utilities/web_ui/base_page.py\", line 34, in __wait_until_element_visible\n    return self.__wait.until(EC.visibility_of_element_located(locator))\n  File \"/home/ubuntu/PycharmProjects/UkrNet_portfolio/.venv/lib/python3.10/site-packages/selenium/webdriver/support/wait.py\", line 105, in until\n    raise TimeoutException(message, screen, stacktrace)\n"}, "start": 1720946905306, "stop": 1720946915516}], "parameters": [{"name": "contact", "value": "'PHONE'"}], "start": 1720946905306, "stop": 1720946915517, "uuid": "0e5efc28-97a9-4171-9655-afc023060d77", "historyId": "7573f0e876968d929bb039e69ae4ba75", "testCaseId": "f5e06f46602ac760aca4dc6aa467f14e", "fullName": "UkrNet.tests.test_login_page.TestLoginPage#test_contacts_content", "labels": [{"name": "severity", "value": "normal"}, {"name": "parentSuite", "value": "Login Page"}, {"name": "suite", "value": "Footer"}, {"name": "subSuite", "value": "TestLoginPage"}, {"name": "host", "value": "ASUS"}, {"name": "thread", "value": "4234-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "UkrNet.tests.test_login_page"}], "links": [{"type": "tms", "url": "https://app.qase.io/case/PF-31", "name": "Contacts content"}]}